### ISSUE TITLE
 there are some problems on sublimt3 (v3126)

### ISSUE THREAD

**Issue by chenweihan** [ayu-theme/ayu-vim#11]
Hi: 
     there are some problems on sublimt3 (Mac sublime3 v3126). the tree navigation and rename have some layout problems.

 ![d1](https://cloud.githubusercontent.com/assets/1927864/21286262/fc743e38-c489-11e6-8684-db8a76842a52.png)
 ![d2](https://cloud.githubusercontent.com/assets/1927864/21286263/04278bf8-c48a-11e6-9f3d-87297bf4b5c6.png)

**Comment by dempfi** [comment]
Sublime theme is here https://github.com/dempfi/ayu
