### ISSUE TITLE
Install for Vim 8

### ISSUE THREAD

**Issue by timpish** [ayu-theme/ayu-vim#13]
New to Vim (coming from Sublime with your brilliant Ayu Mirage). Not quite understanding the install process. Do these lines just go in my vimrc? I have a ~/.vim directory under home, and a ~/.vimrc file. I know plug-ins work differently with Vim 8 and want to get it right. Also, do you have a Terminal profile or only iTerm?

Just installed vim-plug but still need help. Where do actually put the ayu colorscheme?

**Comment by iamajvillalobos** [comment]
```
set termguicolors
let ayucolor="mirage"
colorscheme ayu
```

the above lines should go to your `.vimrc` file. An example would be like this

```
call plug#begin('~/.config/nvim/plugged')
Plug 'ayu-theme/ayu-vim'
call plug#end()

set termguicolors
let ayucolor="mirage"
colorscheme ayu
```

Make sure that you load the theme after your plugin manager load it like above.
