### ISSUE TITLE
End of line character is not visible.

### ISSUE THREAD

**Issue by ghost** [ayu-theme/ayu-vim#18]
Currently, when running running `set list` command, the EOL character is invisible. As a temporary workaround, setting `hi NonText ctermfg=7 guifg=gray` works.

**Comment by fgrsnau** [comment]
I came across this small problem and fixed it for myself by using the same non-obstrusive color as for the line numberings. Maybe you want to incorporate this small change :)

**Comment by andypea** [comment]
This is a really helpful fix. It would be great to see it merged into the official repo.

Thanks for the nice theme!
