### ISSUE TITLE
Anyone got this theme working inside tmux?

### ISSUE THREAD

**Issue by execb5** [ayu-theme/ayu-vim#20]
The colors get all wrong if I'm using tmux. =(

**Comment by dempfi** [comment]
Hey @execb5, you need to enable true colors in tmux. This theme is true color theme and it needs true color supporting terminal emulator.

**Comment by execb5** [comment]
I did all that and still doesn't work. I'm using iterm2 on OSX.

**Comment by execb5** [comment]
_Complementing my last comment_

These are my vim settings:
<img width="399" alt="0__zsh_" src="https://user-images.githubusercontent.com/6979113/30770216-37f8db8c-a001-11e7-8091-d6386995c389.png">
_Without_ the `&t_8f` and `&t_8b` setting

<img width="409" alt="0__zsh_" src="https://user-images.githubusercontent.com/6979113/30770229-60488164-a001-11e7-9e34-e2790771830b.png">
_With_ the `&t_8f` and `&t_8b` setting

---

Outside tmux it's always correct, I also tried messing with the `$TERM` values but didn't manage to get it working.

**Comment by albertorestifo** [comment]
@execb5 Are you using iTerm2? 

It took me a while to fix true-colors in iTerm2 + tmux. [This did the trick for me.](https://github.com/albertorestifo/dotosx/blob/master/vim/vimrc.vim#L62-L70).

Anyway I suggest closing the issue as it's a problem with your config rather than the theme itself.

**Comment by execb5** [comment]
Even with that true color fix it doesn't work, but thanks, @albertorestifo !

I also think that it must be something with my configuration, but since it works for all other themes I just didn't know where else to ask.

Gonna close the issue, thanks!

**Comment by albertorestifo** [comment]
@execb5 I dig a bit in my dotfiles and I also have this in the tmux config: https://github.com/albertorestifo/dotosx/blob/master/tmux/tmux.conf#L27-L28

It overrides the terminal definition to use one that supports true colors. Did you already try this?

**Comment by execb5** [comment]
I didn't have your [line 27](https://github.com/albertorestifo/dotosx/blob/master/tmux/tmux.conf#L27)
It worked!

Thank you so much, @albertorestifo!

**Comment by alextrastero** [comment]
Incase anyone still runs into this issue. 

Debugging:
run:
`tmux info | grep Tc #Tc: missing`

Add to `.tmux.conf`
`set-option -ga terminal-overrides ',xterm-256color:Tc'`

run:
`tmux info | grep Tc #Tc: true`

**Comment by alexzanderr** [comment]
> Incase anyone still runs into this issue.
> 
> Debugging:
> run:
> `tmux info | grep Tc #Tc: missing`
> 
> Add to `.tmux.conf`
> `set-option -ga terminal-overrides ',xterm-256color:Tc'`
> 
> run:
> `tmux info | grep Tc #Tc: true`
doesnt work for me...

**Comment by alexzanderr** [comment]
>  ',xterm-256color:

wow. man. you helped solve a 4 month problem...
