### ISSUE TITLE
Lightline support

### ISSUE THREAD

**Issue by garand** [ayu-theme/ayu-vim#21]
Would you consider adding theme support for [Lightline](https://github.com/itchyny/lightline.vim)?

**Comment by dempfi** [comment]
@garand there is a support for airline now. Thanks to @scvsh. If someone does create a PR for lightline I would gladly merge it.

**Comment by yarisgutierrez** [comment]
I'm currently working on a lightline theme for ayu, which can be found here https://github.com/yarisgutierrez/ayu-lightline. As of now, the mirage theme is completed (some additional tweaks to come), with plans to fit the "light" and "dark" themes soon.

**Comment by oblitum** [comment]
@yarisgutierrez nice work, I came here hoping to find the light version..

**Comment by yarisgutierrez** [comment]
@oblitum Hey! I've been busy with work, but I am still planning on releasing these at some point before the end of the year. Thanks for putting this back on my radar!

**Comment by oblitum** [comment]
OK, I've noticed there's a pull now though https://github.com/ayu-theme/ayu-vim/pull/32, but competition is fine. My dark theme of choice is deep-space, now I need a light version for it.
![14 24 18_28-11-18](https://user-images.githubusercontent.com/1269815/49167603-dc922800-f31c-11e8-9ad5-7bd4d5fc357f.png)
