### ISSUE TITLE
Support for dark?

### ISSUE THREAD

**Issue by SephVelut** [ayu-theme/ayu-vim#28]
Seems like only there is only the mirage syntax colors. Setting `let ayucolor="dark"` enables the dark background and gui colors of the theme but not the syntax

Actual colors
<img width="681" alt="screen shot 2018-06-11 at 8 29 03 pm" src="https://user-images.githubusercontent.com/4496783/41263644-3d4a766c-6db6-11e8-9a7a-59bad95b52ca.png">

Expected colors
<img width="179" alt="screen shot 2018-06-11 at 8 29 58 pm" src="https://user-images.githubusercontent.com/4496783/41263654-49bd624c-6db6-11e8-8ee9-d14c1bbb9780.png">

**Comment by richban** [comment]
How was this issue resolved because I still have the same problem.

**Comment by SephVelut** [comment]
It wasn't. After looking at the code it became known to me that the dark option did nothing.

**Comment by richban** [comment]
Yeah it was clear as well after I have checked the code colors.
