### ISSUE TITLE
Theme not working in screen sessions

### ISSUE THREAD

**Issue by sobrinho** [ayu-theme/ayu-vim#3]
For some reason the theme isn't working on screen sessions, look the differences.

<img width="1280" alt="screen shot 2016-10-17 at 18 41 32" src="https://cloud.githubusercontent.com/assets/26460/19454842/6c1c4a12-9499-11e6-85d1-30eaa71b0de6.png">
<img width="1280" alt="screen shot 2016-10-17 at 18 41 25" src="https://cloud.githubusercontent.com/assets/26460/19454844/6c4b7a26-9499-11e6-84a2-5c62e618b0e0.png">

I'm trying to figure out what is happening, everything is fine on tmux.

The same happens on vim and neovim.

**Comment by dempfi** [comment]
@sobrinho seems you need to enable true colors in screen. take a look at this commit http://git.savannah.gnu.org/cgit/screen.git/commit/?id=9668a1ab00fea2096555a33cb962cc865b86e74a

**Comment by sobrinho** [comment]
I'm trying to figure it out.

It is a compile flag or a runtime flag or both?

I tried to clone the screen source and do `./configure --truecolor` also `--enable-truecolor` and `--with-truecolor` and all of them is unknown 😞

**Comment by dempfi** [comment]
@sobrinho you have to create `.screenrc` in HOME with `truecolor on`. at least this is what I understood from the [docs](http://git.savannah.gnu.org/cgit/screen.git/tree/src/doc/screen.1?id=9668a1ab00fea2096555a33cb962cc865b86e74a#n137).

**Comment by sobrinho** [comment]
Yes, seems like that but the master branch is not building right on OS X and homebrew is broken to build from HEAD: https://github.com/Homebrew/homebrew-dupes/issues/668

Trying to fix it here :(

**Comment by sobrinho** [comment]
Anyway, this is not a issue from ayu-theme itself, so, I'm closing and moving on (I can use tmux if is not possible to compile the master screen).
