### ISSUE TITLE
update colors?

### ISSUE THREAD

**Issue by skbolton** [ayu-theme/ayu-vim#34]
It seems like this repo is falling behind the ayu repo. Maybe its time for an update. Also @dempfi has made a repo of just ayu colors. Maybe its time to update the build to leverage that node package? I would be willing to do this work if you are okay with it?

**Comment by dempfi** [comment]
Hi @skbolton, you're right. This theme is falling behind, tho I don't have much time to come up and test throughoutly an update that would utilize colours from the npm package. So any help is really welcome and appreciated.

**Comment by skbolton** [comment]
Oh awesome I didn’t realize you were the maintainer of this repo! Yeah I wouldn’t mind nudging this along. I haven’t done vim themes before so I will appreciate any feedback you have as the pr’s come through
