### ISSUE TITLE
NerdTree arrow char used in the screenshot?

### ISSUE THREAD

**Issue by Alanxyz** [ayu-theme/ayu-vim#38]
I love this colorscheme. I tankful that you share the font, and identline's char, but, what are the chars used in the nerdtree dir arrows?

**Comment by dempfi** [comment]
This is the config with chars for nerdtree

```
" NERDTree {{
let NERDTreeMinimalUI = 1
let g:NERDTreeDirArrowExpandable = ''
let g:NERDTreeDirArrowCollapsible = ''
"}}
```

**Comment by Eoin-McMahon** [comment]
Is there a specific font needed to display these characters? if so what is it?

**Comment by mvllow** [comment]
@Eoin-McMahon according to https://github.com/ayu-theme/ayu-vim#indent-line it's Roboto Mono for Powerline, available in the repo
