### ISSUE TITLE
airline: There is an error in theme "ayu".

### ISSUE THREAD

**Issue by panosl** [ayu-theme/ayu-vim#41]
This message appears when you set the ayu theme in Neovim 0.4

**Comment by bovarysme** [comment]
This bug was introduced by 6375cd8. Line 87 in the file [autoload/airline/themes/ayu.vim](https://github.com/ayu-theme/ayu-vim/blob/master/autoload/airline/themes/ayu.vim#L87) needs to be replaced with `let s:I2 = s:Array('base6', 'base3')`.
