### ISSUE TITLE
Change ayucolor from neovim command line

### ISSUE THREAD

**Issue by mrassili** [ayu-theme/ayu-vim#46]
Hi

I have the variable `ayucolor` set to dark in my `init.vim` but sometimes I want to change it to `light` temporarily. I tried `:let ayucolor='white'` in neovim command line, it works when I echo it. But actually it doesn't change. it's still dark

I don't know if I should run something after to update the interface that I am not aware of? and if it can be automated somehow?

**Comment by mrassili** [comment]
got my answer on Reddit. :)

**Comment by mvllow** [comment]
@mrassili would you mind sharing the answer here or a link to the reddit? thanks!

**Comment by mrassili** [comment]
ah sorry, here you go:
> From https://github.com/ayu-theme/ayu-vim, it seems you should be setting `let ayucolor="light"` instead of `let ayucolor="white"`. Then run `colorscheme ayu` again if needed
