### ISSUE TITLE
The row numbers are too dim

### ISSUE THREAD

**Issue by mroavi** [ayu-theme/ayu-vim#49]
I can barely see the row numbers when using `let g:gruvbox_contrast_dark='medium'`. With enough light reflecting on the screen, they become unnoticeable. Would it be possible to make them somewhat lighter? I use them all the time for relative jumping between rows.

It would be great if their color could be set to that of the comments which display a bit lighter.

![Screenshot from 2020-04-24 17-44-06](https://user-images.githubusercontent.com/19517248/80231161-4407f080-8653-11ea-9dc7-8542ef157503.png)

**Comment by dempfi** [comment]
@mroavi, I would not recommend to use dark version in lid environment — it's not optimized for that. It's optimized for the opposite :D. Mirage on the other hand was meant to be used in dim environment. Can you try it?

**Comment by mroavi** [comment]
Sure. But note that these numbers are not that easy to read even in dark environments.
