### ISSUE TITLE
Sign Column too narrow for symbols

### ISSUE THREAD

**Issue by samundra** [ayu-theme/ayu-vim#50]
I tried the theme and like it. However, The Sign column seems to be narrow. Can we increase it a bit and remove the background from error. As you can see in screenshot below, I have tried with all three version. Anyway to get rid of red background that is showing up on signcolumn.

## Mirage Theme

![Screen Shot 2020-05-03 at 11 59 35](https://user-images.githubusercontent.com/760855/80899148-d6d11b00-8d36-11ea-9c75-6bc2911f67da.png)

## Dark Theme
![Screen Shot 2020-05-03 at 12 03 25](https://user-images.githubusercontent.com/760855/80899142-bc973d00-8d36-11ea-9618-6aca61137046.png)

## Light Theme
![Screen Shot 2020-05-03 at 12 02 15](https://user-images.githubusercontent.com/760855/80899144-c7ea6880-8d36-11ea-9c14-5d3e0763a0ca.png)

**Comment by richban** [comment]
The colors don't seem to be aligned with the screenshot. What happened to the dark (black) color?

**Comment by samundra** [comment]
> The colors don't seem to be aligned with the screenshot.
- Yes, That was the problem, the background was set to red.

> What happened to the dark (black) color?
- I tried with all of the variations. All of them have same result. 

ALE uses `:hi Error` for error and `:hi Todo` for warnings. So, The fix would be override these highlights manually using custom theme. I have found exact same problem with other themes as well and now I override them with custom color theme.

I believe, we can close this issue as it can be fixed by users and do not need any change in original theme itself.

What do you suggest?
