### ISSUE TITLE
What happened to the theme?

### ISSUE THREAD

**Issue by richban** [ayu-theme/ayu-vim#52]
What happened to the colorscheme?

It seems to me that the colors are not aligned with the `ayu-colors` nor the screenshots in the `README.md`.

How can I have the dark colorsheme from the screenshot?

I have installed the plugin and the result is not really satisfying.

![Screen Shot 2020-05-27 at 9 58 29 PM](https://user-images.githubusercontent.com/6967088/83067274-b01cb080-a066-11ea-9650-22c1703719e8.png)

**Comment by sheerun** [comment]
Probably you need `set termguicolors`

**Comment by adelarsq** [comment]
@richban Which terminal are you using?

**Comment by richban** [comment]
@adelarsq I am using ITerm2 does it somehow overwrites the collors?

**Comment by adelarsq** [comment]
> I am using ITerm2 does it somehow overwrites the collors?

I don't think so. I also use iTerm2.

For me dark shows like this:

<img width="645" alt="Captura de Tela 2020-07-02 às 18 32 16" src="https://user-images.githubusercontent.com/430272/86411066-62f9b300-bc92-11ea-81e7-e5a40da9895b.png">

And for mirage shows like this:

<img width="636" alt="Captura de Tela 2020-07-02 às 18 35 25" src="https://user-images.githubusercontent.com/430272/86411279-e2878200-bc92-11ea-9984-c79fe31ed042.png">

Did you tried mirage? I prefer mirage over dark.

**Comment by richban** [comment]
I just give up and migrated to `gruvbox` but thanks, guys!
