### ISSUE TITLE
Move term colors to different repository

### ISSUE THREAD

**Issue by peteyycz** [ayu-theme/ayu-vim#6]
It would be really nice to have support for other terminals out there.
This site could be helpful generating other configurations http://terminal.sexy/ :)

**Comment by dempfi** [comment]
hi @peteyy, thx for suggestion will do this soon 👍

**Comment by amckinlay** [comment]
@dempfi can you submit your themes to https://github.com/mbadolato/iTerm2-Color-Schemes? They have scripts to automatically port to different terminal emulators, too. There seems to be existing themes for ayu-light and ayu-dark, but if this repo contains the official ones, they should probably be replaced.

**Comment by amckinlay** [comment]
Also, if you do that, the `*.termcolors` files should be specified using

    <key>Color Space</key>
    <string>sRGB</string>

instead.

**Comment by skbolton** [comment]
@dempfi How do you want help on this one?
