### ISSUE TITLE
when I set the light  theme, the cusor fade...........

### ISSUE THREAD

**Issue by cyt-codemaker** [ayu-theme/ayu-vim#65]
when I edit in normal-mode and insert-mode, I can't find my cursor because the cursor and the background are all light. What should I do?

**Comment by Luxed** [comment]
This is either an issue with your Terminal, Client (gvim, nvim-qt, etc.) or you might want `:h guicursor`.
Here's example's of different terminal behavior:
- Kitty: white cursor in dark mode and light gray in light mode. Perfectly distinguishable all the time.
- Alacritty: cursor color are reversed background and foreground. Very easy to find it.
- Windows Terminal: Always white. I had to change it to something like a very light blue to make it visible in both dark and light theme.

**Comment by cyt-codemaker** [comment]
> This is either an issue with your Terminal, Client (gvim, nvim-qt, etc.) or you might want .
> Here's example's of different terminal behavior:`:h guicursor`
> 
> * Kitty: white cursor in dark mode and light gray in light mode. Perfectly distinguishable all the time.
> * Alacritty: cursor color are reversed background and foreground. Very easy to find it.
> * Windows Terminal: Always white. I had to change it to something like a very light blue to make it visible in both dark and light theme.

Thank you very much. I've solved it.
