### ISSUE TITLE
Diff colors are definetly not right

### ISSUE THREAD

**Issue by carljohnson93** [ayu-theme/ayu-vim#66]
Here's how deleted lines diff color look:

![Снимок экрана 2021-06-19 в 11 03 11](https://user-images.githubusercontent.com/47556468/122635678-033c2800-d0ee-11eb-8063-a976c361ec1c.png)

I expected the color to be red.. How that can be fixed?

**Comment by carljohnson93** [comment]
I forgot mentioning that I'm using `let ayucolor='light'`

**Comment by panosl** [comment]
I'd suggest you check out https://github.com/Luxed/ayu-vim @Luxed branch, it's more up to date, and actually accepts Issues and PRs

**Comment by carljohnson93** [comment]
Thank you @panosl

**Comment by carljohnson93** [comment]
I've submitted an [issue](https://github.com/Luxed/ayu-vim/issues/11) to Luxed/ayu-vim repo
