### ISSUE TITLE
error when setting colorscheme first

### ISSUE THREAD

**Issue by kuntau** [ayu-theme/ayu-vim#7]
setting `colors ayu` without specifying `let ayucolor=xxx` failed to apply the colorscheme

setting `colors ayu` first then `let ayucolor=xxx` will give bunch of error before applying the color

setting `let ayucolor=xxx`  first then `colors ayu` works perfectly

I don't know if this is intentional or not

Test on `neovim v0.2.0-dev` and `vim v8.0`

**Comment by dempfi** [comment]
Kinda, I missed to add default value for `ayucolor` :)

**Comment by agreco** [comment]
I'm getting a stream of errors regardless of placement `color` and `aycolor` vars, here is my colour setup:
```
let $NVIM_TUI_ENABLE_TRUE_COLOR=1
let $NVIM_TUI_ENABLE_CURSOR_SHAPE=1
colorscheme ayu
let ayucolor="mirage"
if (has("termguicolors"))
 set termguicolors
endif
syntax enable
```

**Comment by dempfi** [comment]
@agreco Try to activate truecolors first, then set ayucolor and set colorscheme after.

**Comment by agreco** [comment]
I've done that, but still getting the errors..

**Comment by dempfi** [comment]
@agreco hm, are you sure your VIM have support for true colors, if yes, can you please provide version

**Comment by agreco** [comment]
sure.. the version I have running is neovim 0.1.6 and vim 8.0
