### ISSUE TITLE
let ayucolor = "mirage" launch a popup

### ISSUE THREAD

**Issue by ebdm13** [ayu-theme/ayu-vim#80]
when i write `let ayucolor = "mirage"` it launch "hit the enter key or enter a command"

that's my vimrc
```vim-script
call plug#begin()
Plug "ayu-theme/ayu-vim"
call plug#end()
set termguicolors
let ayucolor = "mirage"
colorscheme ayu
``` 
and it seems that the `let ayucolor = "mirage"` line throws  a popup.
can someone tell me why and how to avoid it please

**Comment by Luxed** [comment]
I'm pretty sure this is a duplicate of #73.
And as instructed there, you are better off using my fork: https://github.com/luxed/ayu-vim.

**Comment by ebdm13** [comment]
Thanks
