### ISSUE TITLE
problem in line 275 in ayu.vim when mirage colors activated

### ISSUE THREAD

**Issue by vijaypanchalr3** [ayu-theme/ayu-vim#81]

**Comment by vijaypanchalr3** [comment]
Sorry, i'm not that good in vimrc programming to find problem. Just started vim for basic editing on the go.

**Comment by Luxed** [comment]
Use [my fork of the theme](https://github.com/Luxed/ayu-vim) instead. I'm still maintaining it and fixing issues when they're reported.
